"""
Tests for setup_wizard.py and server_launcher.py utility functions.

These cover all testable logic without launching a GUI window.

Run with:
    pytest _test_/unit/test_setup_wizard.py -v
"""

from __future__ import annotations

import json
import os
import platform
import sys
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

# Add repo root to path so we can import setup_wizard without installing
REPO_ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(REPO_ROOT))


# ── Patch out customtkinter before importing setup_wizard (no display needed) ──
# We mock the entire customtkinter module so tests run headless.
import unittest.mock as mock

CTK_MOCK = mock.MagicMock()
sys.modules.setdefault("customtkinter", CTK_MOCK)
sys.modules.setdefault("PIL", mock.MagicMock())
sys.modules.setdefault("PIL.Image", mock.MagicMock())
sys.modules.setdefault("PIL.ImageDraw", mock.MagicMock())
sys.modules.setdefault("pystray", mock.MagicMock())
sys.modules.setdefault("tkinter", mock.MagicMock())
sys.modules.setdefault("tkinter.filedialog", mock.MagicMock())
sys.modules.setdefault("tkinter.messagebox", mock.MagicMock())

# Prevent _bootstrap_deps from running pip during import
with patch("subprocess.check_call"):
    import setup_wizard as sw
    import server_launcher as sl


# ══════════════════════════════════════════════════════════════════════════
# get_os
# ══════════════════════════════════════════════════════════════════════════

@pytest.mark.parametrize("system,expected", [
    ("Windows", "windows"),
    ("Darwin",  "mac"),
    ("Linux",   "linux"),
    ("FreeBSD", "linux"),  # fallthrough to linux
])
def test_get_os(system, expected):
    with patch("platform.system", return_value=system):
        assert sw.get_os() == expected


# ══════════════════════════════════════════════════════════════════════════
# get_claude_desktop_config_path
# ══════════════════════════════════════════════════════════════════════════

def test_config_path_windows():
    with patch("platform.system", return_value="Windows"), \
         patch.dict(os.environ, {"APPDATA": "C:\\Users\\Test\\AppData\\Roaming"}):
        path = sw.get_claude_desktop_config_path()
        assert "Claude" in str(path)
        assert str(path).endswith("claude_desktop_config.json")


def test_config_path_mac():
    with patch("platform.system", return_value="Darwin"), \
         patch("pathlib.Path.home", return_value=Path("/Users/test")):
        path = sw.get_claude_desktop_config_path()
        assert "Application Support" in str(path)
        assert str(path).endswith("claude_desktop_config.json")


def test_config_path_linux():
    with patch("platform.system", return_value="Linux"), \
         patch("pathlib.Path.home", return_value=Path("/home/test")):
        path = sw.get_claude_desktop_config_path()
        assert "Claude" in str(path)
        assert str(path).endswith("claude_desktop_config.json")


# ══════════════════════════════════════════════════════════════════════════
# write_env
# ══════════════════════════════════════════════════════════════════════════

def test_write_env_creates_file(tmp_path):
    with patch("setup_wizard.get_env_path", return_value=tmp_path / ".env"):
        sw.write_env({
            "OBSIDIAN_MCP_VAULT_PATH": "/vault",
            "OBSIDIAN_MCP_LOG_LEVEL": "INFO",
        })
        content = (tmp_path / ".env").read_text()
        assert "OBSIDIAN_MCP_VAULT_PATH=/vault" in content
        assert "OBSIDIAN_MCP_LOG_LEVEL=INFO" in content


def test_write_env_includes_header(tmp_path):
    with patch("setup_wizard.get_env_path", return_value=tmp_path / ".env"):
        sw.write_env({"K": "V"})
        content = (tmp_path / ".env").read_text()
        assert "generated by setup wizard" in content


def test_write_env_omits_empty_api_key(tmp_path):
    """API key with empty value should still be written — caller controls what's passed."""
    with patch("setup_wizard.get_env_path", return_value=tmp_path / ".env"):
        sw.write_env({"OBSIDIAN_MCP_ADAPTER_API_KEY": ""})
        content = (tmp_path / ".env").read_text()
        assert "OBSIDIAN_MCP_ADAPTER_API_KEY=" in content


# ══════════════════════════════════════════════════════════════════════════
# merge_claude_desktop_config
# ══════════════════════════════════════════════════════════════════════════

def test_merge_creates_new_config(tmp_path):
    cfg_path = tmp_path / "claude_desktop_config.json"
    with patch("setup_wizard.get_claude_desktop_config_path", return_value=cfg_path):
        ok, msg = sw.merge_claude_desktop_config(
            ["uv", "run", "obsidian-mcp"],
            {"OBSIDIAN_MCP_VAULT_PATH": "/vault"},
        )
    assert ok
    data = json.loads(cfg_path.read_text())
    assert "obsidian-mcp" in data["mcpServers"]
    assert data["mcpServers"]["obsidian-mcp"]["command"] == "uv"
    assert data["mcpServers"]["obsidian-mcp"]["args"] == ["run", "obsidian-mcp"]


def test_merge_preserves_existing_servers(tmp_path):
    cfg_path = tmp_path / "claude_desktop_config.json"
    existing = {
        "mcpServers": {
            "another-mcp": {"command": "python", "args": ["-m", "other"]}
        }
    }
    cfg_path.write_text(json.dumps(existing))
    with patch("setup_wizard.get_claude_desktop_config_path", return_value=cfg_path):
        ok, _ = sw.merge_claude_desktop_config(["uv", "run", "obsidian-mcp"], {})
    assert ok
    data = json.loads(cfg_path.read_text())
    assert "another-mcp" in data["mcpServers"], "Existing server was overwritten!"
    assert "obsidian-mcp" in data["mcpServers"]


def test_merge_overwrites_existing_obsidian_mcp_entry(tmp_path):
    cfg_path = tmp_path / "claude_desktop_config.json"
    existing = {
        "mcpServers": {
            "obsidian-mcp": {"command": "old_cmd", "args": []}
        }
    }
    cfg_path.write_text(json.dumps(existing))
    with patch("setup_wizard.get_claude_desktop_config_path", return_value=cfg_path):
        ok, _ = sw.merge_claude_desktop_config(["uv", "run", "obsidian-mcp"], {})
    assert ok
    data = json.loads(cfg_path.read_text())
    assert data["mcpServers"]["obsidian-mcp"]["command"] == "uv"


def test_merge_fails_on_invalid_json(tmp_path):
    cfg_path = tmp_path / "claude_desktop_config.json"
    cfg_path.write_text("NOT VALID JSON {{{")
    with patch("setup_wizard.get_claude_desktop_config_path", return_value=cfg_path):
        ok, msg = sw.merge_claude_desktop_config(["uv", "run", "obsidian-mcp"], {})
    assert not ok
    assert "not valid JSON" in msg


def test_merge_atomic_write(tmp_path):
    """Verify .tmp is cleaned up and final file is valid."""
    cfg_path = tmp_path / "claude_desktop_config.json"
    tmp_file = cfg_path.with_suffix(".tmp")
    with patch("setup_wizard.get_claude_desktop_config_path", return_value=cfg_path):
        sw.merge_claude_desktop_config(["uv", "run", "obsidian-mcp"], {})
    assert not tmp_file.exists(), ".tmp file was not cleaned up"
    assert cfg_path.exists()


# ══════════════════════════════════════════════════════════════════════════
# build_server_command
# ══════════════════════════════════════════════════════════════════════════

def test_build_server_command_contains_uv_and_obsidian_mcp():
    cmd = sl.build_server_command()
    assert "obsidian-mcp" in cmd
    # Must contain the --directory flag
    assert "--directory" in cmd


def test_build_server_command_uses_project_root():
    root = sl.get_project_root()
    cmd  = sl.build_server_command()
    idx  = cmd.index("--directory")
    assert cmd[idx + 1] == str(root)


# ══════════════════════════════════════════════════════════════════════════
# ServerProcess — unit tests (no real subprocess)
# ══════════════════════════════════════════════════════════════════════════

def make_server() -> sl.ServerProcess:
    return sl.ServerProcess(on_log=lambda m: None, on_status_change=lambda s: None)


def test_server_initial_status_is_stopped():
    s = make_server()
    assert s.status == "stopped"
    assert not s.is_running()


def test_server_start_sets_running(tmp_path):
    import threading as _threading
    statuses = []
    reached_running = _threading.Event()

    def on_status(s):
        statuses.append(s)
        if s == "running":
            reached_running.set()

    s = sl.ServerProcess(on_log=lambda m: None, on_status_change=on_status)
    mock_proc = MagicMock()
    mock_proc.poll.return_value = None
    mock_proc.stdout = iter([])
    wait_released = _threading.Event()
    mock_proc.wait.side_effect = lambda: wait_released.wait()
    mock_proc.returncode = 0

    with patch("subprocess.Popen", return_value=mock_proc):
        s.start()

    reached_running.wait(timeout=2)
    assert "running" in statuses
    wait_released.set()


def test_server_stop_sets_stopped(tmp_path):
    s = make_server()
    mock_proc = MagicMock()
    mock_proc.poll.return_value = None
    mock_proc.stdout = iter([])
    mock_proc.returncode = 0

    with patch("subprocess.Popen", return_value=mock_proc):
        s.start()

    mock_proc.poll.return_value = 0   # process has exited after terminate()
    s.stop()
    assert s.status == "stopped"
    assert not s.is_running()


def test_server_start_twice_does_not_spawn_second_process():
    s = make_server()
    mock_proc = MagicMock()
    mock_proc.poll.return_value = None
    mock_proc.stdout = iter([])

    with patch("subprocess.Popen", return_value=mock_proc) as popen_mock:
        s.start()
        s.start()   # second call — should be no-op
    assert popen_mock.call_count == 1


def test_server_stop_when_not_running_is_safe():
    s = make_server()
    s.stop()   # should not raise
    assert s.status == "stopped"


def test_server_logs_startup_command():
    logs = []
    s = sl.ServerProcess(on_log=logs.append, on_status_change=lambda _: None)
    mock_proc = MagicMock()
    mock_proc.poll.return_value = None
    mock_proc.stdout = iter([])

    with patch("subprocess.Popen", return_value=mock_proc):
        s.start()

    assert any("obsidian-mcp" in l for l in logs)


# ══════════════════════════════════════════════════════════════════════════
# Desktop shortcut (smoke tests — verify OS dispatch, not actual file)
# ══════════════════════════════════════════════════════════════════════════

def test_create_shortcut_windows_calls_powershell():
    with patch("platform.system", return_value="Windows"), \
         patch("subprocess.check_call") as mock_call, \
         patch("pathlib.Path.home", return_value=Path("/fake/home")):
        # Patch Desktop to a tmp dir to avoid actually writing
        fake_desktop = Path("/fake/home/Desktop")
        with patch.object(Path, "mkdir", return_value=None), \
             patch("builtins.open", mock.mock_open()):
            sw.create_desktop_shortcut()
    # powershell should have been called
    assert mock_call.called
    args = mock_call.call_args[0][0]
    assert "powershell" in args[0].lower() or "powershell" in args


def test_create_shortcut_mac_creates_command_file(tmp_path):
    fake_desktop = tmp_path
    with patch("platform.system", return_value="Darwin"), \
         patch("pathlib.Path.home", return_value=tmp_path.parent):
        # Override desktop to be tmp_path
        with patch("setup_wizard.Path.home", return_value=tmp_path.parent):
            desktop_file = tmp_path / "Obsidian MCP.command"
            # We just check the function doesn't raise
            try:
                sw.create_desktop_shortcut()
            except Exception:
                pass   # May fail because /fake/Desktop doesn't exist — that's fine for this smoke test


def test_create_shortcut_linux_creates_desktop_entry(tmp_path):
    with patch("platform.system", return_value="Linux"), \
         patch("pathlib.Path.home", return_value=tmp_path):
        desktop = tmp_path / "Desktop"
        desktop.mkdir()
        result = sw.create_desktop_shortcut()
        entry = desktop / "Obsidian MCP.desktop"
        if result:
            assert entry.exists()
            content = entry.read_text()
            assert "[Desktop Entry]" in content
            assert "Type=Application" in content


# ══════════════════════════════════════════════════════════════════════════
# install_uv (smoke — patches subprocess)
# ══════════════════════════════════════════════════════════════════════════

def test_install_uv_success():
    with patch("platform.system", return_value="Linux"), \
         patch("subprocess.run") as mock_run:
        mock_run.return_value = MagicMock(returncode=0, stdout="installed", stderr="")
        ok, out = sw.install_uv()
    assert ok
    assert "installed" in out


def test_install_uv_failure():
    with patch("platform.system", return_value="Linux"), \
         patch("subprocess.run") as mock_run:
        mock_run.return_value = MagicMock(returncode=1, stdout="", stderr="network error")
        ok, out = sw.install_uv()
    assert not ok
    assert "network error" in out


def test_install_uv_windows_uses_powershell():
    with patch("platform.system", return_value="Windows"), \
         patch("subprocess.run") as mock_run:
        mock_run.return_value = MagicMock(returncode=0, stdout="ok", stderr="")
        sw.install_uv()
    args = mock_run.call_args[0][0]
    assert "powershell" in " ".join(args).lower()


# ══════════════════════════════════════════════════════════════════════════
# run_uv_sync (smoke)
# ══════════════════════════════════════════════════════════════════════════

def test_run_uv_sync_success():
    logs = []
    mock_proc = MagicMock()
    mock_proc.stdout = iter(["Resolved 12 packages\n", "Installed 12 packages\n"])
    mock_proc.wait.return_value = None
    mock_proc.returncode = 0

    with patch("subprocess.Popen", return_value=mock_proc):
        ok, output = sw.run_uv_sync(logs.append)
    assert ok
    assert any("Resolved" in l for l in logs)


def test_run_uv_sync_failure():
    logs = []
    mock_proc = MagicMock()
    mock_proc.stdout = iter(["error: something failed\n"])
    mock_proc.wait.return_value = None
    mock_proc.returncode = 1

    with patch("subprocess.Popen", return_value=mock_proc):
        ok, output = sw.run_uv_sync(logs.append)
    assert not ok
